### ISSUE TITLE
Allow default externs to be passed in

### ISSUE THREAD

**Issue by alexeagle** [angular/closure-to-dts#15]
Using CommandLineRunner.getDefaultExterns doesn't work well inside google, where the default externs are typically passed into the program.

cc @mprobst

**Comment by alexeagle** [comment]
We will need a way to parse the command line, both for distinguishing externs inputs from those to emit, and for providing the output directory.
I've always used https://github.com/kohsuke/args4j in the past, and it seems to be currently maintained.
Alternatively, we could do something cheap like I have currently, where we just scan for magic args like "--externs" or "-o" and then switch modes while pop`ing subsequent argv`s.

**Comment by mprobst** [comment]
I think I remember using args4j, and it was good. Your call if it's warranted, but my hunch is that eventually, we're better off doing this the proper way.
