### ISSUE TITLE
Emitting empty parens (bad syntax) when a type is unknown

### ISSUE THREAD

**Issue by alexeagle** [angular/closure-to-dts#18]
```
/**
 * @return {Element} The visible header element.
 */
goog.ui.Zippy.prototype.getVisibleHeaderElement = function() {
}
```
produces
```
getVisibleHeaderElement ( ) : ( ) ;
```

**Comment by rkirov** [comment]
The real issue here is that the tools was ran in a more permissive mode, where the extern was not present, but no error was thrown.

I am adding a test to run the tool in the presence of browser externs and closing the issue.
