### ISSUE TITLE
subclasses with different constructor params break static call method gen

### ISSUE THREAD

**Issue by rkirov** [angular/closure-to-dts#76]
For example if B extends A and takes string instead of number, we generate:

```javascript
declare namespace f {
	class A {
		constructor(n: number);
		static call(a: A, n: number);
	}

	class B extends A {
		constructor(s: string);
		static call(b: B, n: string);
	}
}
```

TS barfs on the static call for B which is required to subtype A's functional type. See 'oog.fx.dom.PredefinedEffect' and 'Animation' for closure lib repro.

Maybe we should not output `call` and `apply` for constructor functions until someone really needs them. I can't come up with a good need for using those in sane TS code.

**Comment by mprobst** [comment]
+1 on not emitting `call`/`apply` for ctors, AFAIK it's even illegal to use
`apply` on an ES6 class, so this is bound to only cause confusion.

Rado Kirov <notifications@github.com> schrieb am Mi., 2. Sep. 2015 um
02:47 Uhr:

**Comment by rkirov** [comment]
Turns out these static methods are only output if they are used somewhere else (most likely for implementing super constructor calls).

**Comment by rkirov** [comment]
I can't get the following Closure code to compile in our test harness:

```javascript
/**
 * @constructor
 * @param {number} n
 */
multi_class.A = function(n) {
  /** @type {number} */
  this.a = n;
};

/**
 * @constructor
 * @extends {multi_class.A}
 */
multi_class.B = function() {
  /** @type {number} */
  this.b = 1;
  multi_class.A.call(this, 0);
};
goog.inherits(multi_class.B, multi_class.A);
```

Closure complains that it can't find `call` on `multi_class.A`, even though that's the pattern that `goog.fx.dom.PredefinedEffect` and subclasses use.

Works fine in the standalone [cl compiler](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540use_closure_library%2520true%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Agoog.provide('multi_class')%253B%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520n%250A%2520*%252F%250Amulti_class.A%2520%253D%2520function(n)%2520%257B%250A%2520%2520%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250A%2520%2520this.a%2520%253D%2520n%253B%250A%257D%253B%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540extends%2520%257Bmulti_class.A%257D%250A%2520*%252F%250Amulti_class.B%2520%253D%2520function()%2520%257B%250A%2520%2520%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250A%2520%2520this.b%2520%253D%25201%253B%250A%2520%2520multi_class.A.call(this%252C%25200)%253B%250A%257D%253B%250Agoog.inherits(multi_class.B%252C%2520multi_class.A)%253B%250A%250Amulti_class.B.prototype.foo%2520%253D%2520function()%2520%257Breturn%2520this.a%2520%252B%2520this.b%253B%257D%250A%250Awindow%255B'B'%255D%2520%253D%2520multi_class.B%253B%250AMyClass.prototype%255B'foo'%255D%2520%253D%2520MyClass.prototype.foo%253B%250A) which probably means we are have some different flag setting.

**Comment by rkirov** [comment]
cc @matrixfrog

**Comment by MatrixFrog** [comment]
I think it would still be good to know why the type system works this way, but I suspect the new type system is a little more sane so I'm not overly worried about it.
