### ISSUE TITLE
Unstable iteration order

### ISSUE THREAD

**Issue by alexeagle** [angular/closure-to-dts#83]
When running tests on OSX with JDK8, the order of declarations in the .d.ts files differs from the golden files.

**Comment by alexeagle** [comment]
As a workaround, switching to JDK7 fixes this.

**Comment by mprobst** [comment]
That sounds like we need to use a `LinkedHashMap` somewhere?

Alex Eagle <notifications@github.com> schrieb am Do., 3. Sep. 2015 um
22:11 Uhr:

**Comment by alexeagle** [comment]
I started looking into it - I suspect this is in closure compiler, since we
just create iterator's on collections they return. At least in one
location, closure compiler is already using a linkedhashmap, with insertion
ordering. But I'm sure there are many other collections where the data is
shuffled.
